<?xml version="1.0"?>
<package format="3">
  <name>jetpilot_vesc_interface</name>
  <version>0.1.0</version>
  <description>JetPilot vehicle interface for VESC based vehicles</description>
  <maintainer email="your_email@example.com">Your Name</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake_auto</buildtool_depend>

  <depend>jetpilot_msgs</depend>
  <depend>rclcpp</depend>
  <depend>std_msgs</depend>

  <exec_depend>vesc_driver</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>xacro</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
